import React, { FormEvent, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, Check, ChevronDown, Clock3, Copy, Download, FileText, History, Layers3, LogOut, RefreshCw, Search, Send, ShieldCheck, Sparkles, Trash2, XCircle } from 'lucide-react';
import './styles.css';

type QueryStatus = 'idle' | 'loading' | 'success' | 'error';
type ViewName = 'search' | 'batch' | 'history' | 'exports';
type User = { name: string; email: string; role: string };
type QueryResult = { id: string; command: string; status: string; content: string; error?: string | null; createdAt: string; finishedAt?: string | null; elapsedMs: number; requestedBy: string; requestedByEmail: string; batchId?: string | null };
type Batch = { id: string; commandPrefix: string; status: string; total: number; queued: number; processing: number; completed: number; failed: number; cancelled: number; createdAt: string; updatedAt: string; requestedBy: string; requestedByEmail: string; items: QueryResult[] };
type ParsedField = { id: string; label: string; value: string; section: string };
type CommandOption = { command: string; label: string; description: string; placeholder: string; inputMode?: React.HTMLAttributes<HTMLInputElement>['inputMode']; format: (value: string) => string; clean: (value: string) => string };

const TOKEN_KEY = 'painel-consulta-token';
const digits = (value: string) => value.replace(/\D/g, '');
const upper = (value: string) => value.toUpperCase();
const formatCpf = (value: string) => digits(value).slice(0, 11).replace(/^(\d{3})(\d)/, '$1.$2').replace(/^(\d{3})\.(\d{3})(\d)/, '$1.$2.$3').replace(/\.(\d{3})(\d)/, '.$1-$2');
const formatPhone = (value: string) => { const v = digits(value).slice(0, 11); if (v.length <= 2) return v ? `(${v}` : ''; if (v.length <= 7) return `(${v.slice(0, 2)}) ${v.slice(2)}`; return `(${v.slice(0, 2)}) ${v.slice(2, 7)}-${v.slice(7)}`; };
const formatCnpj = (value: string) => digits(value).slice(0, 14).replace(/^(\d{2})(\d)/, '$1.$2').replace(/^(\d{2})\.(\d{3})(\d)/, '$1.$2.$3').replace(/\.(\d{3})(\d)/, '.$1/$2').replace(/(\d{4})(\d)/, '$1-$2');
const formatCep = (value: string) => digits(value).slice(0, 8).replace(/^(\d{5})(\d)/, '$1-$2');
const formatPlate = (value: string) => upper(value.replace(/[^a-zA-Z0-9]/g, '')).slice(0, 7);
const identity = (value: string) => value;

const commandOptions: CommandOption[] = [
  { command: '/cpf', label: 'CPF', description: 'Buscar pessoa por CPF', placeholder: '000.000.000-00', inputMode: 'numeric', format: formatCpf, clean: digits },
  { command: '/numero', label: 'Celular', description: 'Buscar pessoa por número', placeholder: '(11) 91111-1111', inputMode: 'tel', format: formatPhone, clean: digits },
  { command: '/email', label: 'E-mail', description: 'Buscar por e-mail', placeholder: 'nome@email.com', inputMode: 'email', format: identity, clean: value => value.trim() },
  { command: '/placa', label: 'Placa', description: 'Buscar veículo', placeholder: 'ABC1D23', format: formatPlate, clean: formatPlate },
  { command: '/nome1', label: 'Nome completo', description: 'Buscar pelo nome', placeholder: 'Digite o nome completo', format: upper, clean: value => value.trim() },
  { command: '/cep1', label: 'CEP', description: 'Consulta por CEP', placeholder: '00000-000', inputMode: 'numeric', format: formatCep, clean: digits },
  { command: '/cbo', label: 'CBO', description: 'Consulta por CBO', placeholder: '000000', inputMode: 'numeric', format: value => digits(value).slice(0, 6), clean: digits },
  { command: '/profissao', label: 'Profissão', description: 'Buscar por profissão', placeholder: 'Digite a profissão', format: upper, clean: value => value.trim() },
  { command: '/empresa', label: 'Empresa', description: 'Buscar por empresa', placeholder: 'Digite a empresa', format: upper, clean: value => value.trim() },
  { command: '/cnpj', label: 'CNPJ', description: 'Buscar empresa por CNPJ', placeholder: '00.000.000/0000-00', inputMode: 'numeric', format: formatCnpj, clean: digits },
];

function mapQuery(data: any): QueryResult {
  return { id: data.id, command: data.command, status: data.status, content: data.content || '', error: data.error, createdAt: data.created_at, finishedAt: data.finished_at, elapsedMs: data.elapsed_ms || 0, requestedBy: data.requested_by, requestedByEmail: data.requested_by_email, batchId: data.batch_id };
}
function mapBatch(data: any): Batch {
  return { id: data.id, commandPrefix: data.command_prefix, status: data.status, total: data.total, queued: data.queued, processing: data.processing, completed: data.completed, failed: data.failed, cancelled: data.cancelled, createdAt: data.created_at, updatedAt: data.updated_at, requestedBy: data.requested_by, requestedByEmail: data.requested_by_email, items: (data.items || []).map(mapQuery) };
}
function parseFields(content: string): ParsedField[] {
  let section = 'Informações'; const fields: ParsedField[] = [];
  content.split(/\r?\n/).forEach((rawLine, index) => { const line = rawLine.trim(); if (!line) return; if (/^>{1,3}\s*/.test(line) || /^[-=]{3,}$/.test(line)) { section = line.replace(/^>{1,3}\s*/, '').replace(/^[-=]+|[-=]+$/g, '').trim() || section; return; } const separatorIndex = line.indexOf(':'); if (separatorIndex <= 0) return; const label = line.slice(0, separatorIndex).trim(); const value = line.slice(separatorIndex + 1).trim(); if (label && value) fields.push({ id: `${index}-${label}`, label, value, section }); });
  return fields;
}
function displayCommand(command: string) { const option = commandOptions.find(item => command.startsWith(`${item.command} `) || command === item.command); return option ? `${option.label}: ${command.slice(option.command.length).trim()}` : command; }
function downloadText(result: QueryResult) { const body = `Consulta: ${displayCommand(result.command)}\nStatus: ${result.status}\nUsuário: ${result.requestedBy}\nData: ${new Date(result.createdAt).toLocaleString('pt-BR')}\nTempo: ${(result.elapsedMs / 1000).toFixed(1)}s\n\n${result.content || result.error || ''}`; const blob = new Blob([body], { type: 'text/plain;charset=utf-8' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `consulta-${result.id}.txt`; anchor.click(); URL.revokeObjectURL(url); }

function App() {
  const [token, setToken] = useState(localStorage.getItem(TOKEN_KEY) || '');
  const [user, setUser] = useState<User | null>(null);
  const [loginEmail, setLoginEmail] = useState(''); const [loginPassword, setLoginPassword] = useState(''); const [loginError, setLoginError] = useState('');
  const [view, setView] = useState<ViewName>('search'); const [selectedCommand, setSelectedCommand] = useState('/cpf'); const [searchValue, setSearchValue] = useState(''); const [batchValues, setBatchValues] = useState('');
  const [status, setStatus] = useState<QueryStatus>('idle'); const [result, setResult] = useState<QueryResult | null>(null); const [errorMessage, setErrorMessage] = useState(''); const [copiedId, setCopiedId] = useState('');
  const [history, setHistory] = useState<QueryResult[]>([]); const [batches, setBatches] = useState<Batch[]>([]); const [activeBatch, setActiveBatch] = useState<Batch | null>(null);

  function authHeaders() { return { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }; }
  function logout() { localStorage.removeItem(TOKEN_KEY); setToken(''); setUser(null); setHistory([]); setBatches([]); setActiveBatch(null); }
  async function copyValue(id: string, value: string) { await navigator.clipboard.writeText(value); setCopiedId(id); window.setTimeout(() => setCopiedId(''), 1400); }
  async function api(path: string, options: RequestInit = {}) { const response = await fetch(path, { ...options, headers: { ...authHeaders(), ...(options.headers || {}) } }); const data = await response.json().catch(() => null); if (response.status === 401) logout(); if (!response.ok) throw new Error(data?.detail || `Erro HTTP ${response.status}`); return data; }
  async function loadHistory() { if (!token) return; const data = await api('/api/history?limit=200'); setHistory(data.map(mapQuery)); }
  async function loadBatches() { if (!token) return; const data = await api('/api/batches?limit=50'); setBatches(data.map(mapBatch)); }
  async function loadBatch(id: string) { const data = await api(`/api/batches/${id}`); const batch = mapBatch(data); setActiveBatch(batch); setBatches(previous => [batch, ...previous.filter(item => item.id !== batch.id)]); if (!['COMPLETED', 'COMPLETED_WITH_ERRORS'].includes(batch.status)) window.setTimeout(() => loadBatch(id).catch(() => undefined), 2000); else loadHistory().catch(() => undefined); }

  useEffect(() => { if (!token) return; fetch('/api/auth/me', { headers: { Authorization: `Bearer ${token}` } }).then(async response => { if (!response.ok) throw new Error(); return response.json(); }).then(data => { setUser(data); loadHistory().catch(() => undefined); loadBatches().catch(() => undefined); }).catch(logout); }, [token]);

  const selectedOption = commandOptions.find(item => item.command === selectedCommand) || commandOptions[0];
  const parsedFields = useMemo(() => parseFields(result?.content || ''), [result]);
  const groupedFields = useMemo(() => parsedFields.reduce<Record<string, ParsedField[]>>((groups, field) => { (groups[field.section] ||= []).push(field); return groups; }, {}), [parsedFields]);

  async function login(event: FormEvent) { event.preventDefault(); setLoginError(''); const response = await fetch('/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: loginEmail, password: loginPassword }) }); const data = await response.json().catch(() => null); if (!response.ok) { setLoginError(data?.detail || 'Não foi possível entrar.'); return; } localStorage.setItem(TOKEN_KEY, data.access_token); setToken(data.access_token); setUser(data.user); setLoginPassword(''); }
  async function runQuery(event: FormEvent) { event.preventDefault(); const cleaned = selectedOption.clean(searchValue); if (!cleaned || status === 'loading') return; setStatus('loading'); setResult(null); setErrorMessage(''); try { const data = await api('/api/queries', { method: 'POST', body: JSON.stringify({ command: `${selectedOption.command} ${cleaned}` }) }); const finished = mapQuery(data); setResult(finished); setStatus(finished.status === 'FAILED' ? 'error' : 'success'); await loadHistory(); } catch (error) { setErrorMessage(error instanceof Error ? error.message : 'Falha na consulta.'); setStatus('error'); } }
  async function runBatch(event: FormEvent) { event.preventDefault(); const values = batchValues.split(/\r?\n|;/).map(item => selectedOption.clean(item)).filter(Boolean); if (!values.length || status === 'loading') return; setStatus('loading'); setErrorMessage(''); try { const data = await api('/api/queries/batch', { method: 'POST', body: JSON.stringify({ command_prefix: selectedOption.command, values }) }); const batch = mapBatch(data); setActiveBatch(batch); setBatches(previous => [batch, ...previous]); setBatchValues(''); setStatus('success'); loadBatch(batch.id).catch(() => undefined); } catch (error) { setErrorMessage(error instanceof Error ? error.message : 'Falha no lote.'); setStatus('error'); } }
  async function cancelBatch(id: string) { const data = await api(`/api/batches/${id}/cancel`, { method: 'POST' }); setActiveBatch(mapBatch(data)); loadBatch(id).catch(() => undefined); }
  async function retryBatch(id: string) { const data = await api(`/api/batches/${id}/retry-failed`, { method: 'POST' }); const batch = mapBatch(data); setActiveBatch(batch); setBatches(previous => [batch, ...previous]); loadBatch(batch.id).catch(() => undefined); }

  if (!token || !user) return <div className="login-shell"><form className="login-card" onSubmit={login}><div className="brand-mark"><Sparkles size={24}/></div><h1>Acessar painel</h1><p>Entre com seu e-mail e senha.</p><label>E-mail</label><input type="email" value={loginEmail} onChange={e => setLoginEmail(e.target.value)} required/><label>Senha</label><input type="password" value={loginPassword} onChange={e => setLoginPassword(e.target.value)} required/>{loginError && <div className="login-error">{loginError}</div>}<button className="primary-button login-button">Entrar</button></form></div>;

  const progress = activeBatch ? Math.round(((activeBatch.completed + activeBatch.failed + activeBatch.cancelled) / Math.max(activeBatch.total, 1)) * 100) : 0;
  return <div className="app-shell compact-sidebar"><aside className="sidebar"><div className="brand"><div className="brand-mark"><Sparkles size={21}/></div><div><strong>Referência</strong><span>Consulta inteligente</span></div></div><nav className="main-nav"><button className={`nav-item ${view === 'search' ? 'active' : ''}`} onClick={() => setView('search')}><Search size={19}/><span>Nova consulta</span></button><button className={`nav-item ${view === 'batch' ? 'active' : ''}`} onClick={() => setView('batch')}><Layers3 size={19}/><span>Consulta em lote</span></button><button className={`nav-item ${view === 'history' ? 'active' : ''}`} onClick={() => { setView('history'); loadHistory(); }}><History size={19}/><span>Histórico</span><span className="nav-count">{history.length}</span></button><button className={`nav-item ${view === 'exports' ? 'active' : ''}`} onClick={() => setView('exports')}><FileText size={19}/><span>Exportações</span></button></nav><div className="user-card"><div className="avatar">{user.name.slice(0,2).toUpperCase()}</div><div><strong>{user.name}</strong><span>{user.role}</span></div><button title="Sair" onClick={logout}><LogOut size={18}/></button></div></aside><main className="content"><header className="topbar"><div><p className="eyebrow">PAINEL DE CONSULTAS</p><h1>{view === 'search' ? 'Buscar informações.' : view === 'batch' ? 'Consulta em lote.' : view === 'history' ? 'Histórico central.' : 'Central de exportações.'}</h1><p className="subtitle">{view === 'batch' ? 'Envie o lote e acompanhe o progresso mesmo saindo da página.' : 'Os resultados agora ficam salvos de forma centralizada por usuário.'}</p></div><div className="status-pill"><span></span>{user.name} conectado</div></header>

  {(view === 'search' || view === 'batch') && <section className="hero-card search-panel"><div className="hero-copy"><div className="hero-icon">{view === 'batch' ? <Layers3 size={22}/> : <Send size={22}/>}</div><div><h2>{view === 'batch' ? 'Nova consulta em lote' : 'Nova consulta'}</h2><p>Selecione o tipo e preencha os valores.</p></div></div><div className="search-type-row"><label>Tipo de consulta</label><div className="select-wrap"><select value={selectedCommand} onChange={e => { setSelectedCommand(e.target.value); setSearchValue(''); }}><>{commandOptions.map(option => <option key={option.command} value={option.command}>{option.label} — {option.description}</option>)}</></select><ChevronDown size={18}/></div></div>{view === 'search' ? <form onSubmit={runQuery} className="query-form"><label>{selectedOption.label}</label><div className="query-row"><div className="input-wrap"><Search size={20}/><input value={searchValue} onChange={e => setSearchValue(selectedOption.format(e.target.value))} placeholder={selectedOption.placeholder} inputMode={selectedOption.inputMode}/></div><button className="primary-button" disabled={status === 'loading'}>{status === 'loading' ? 'Consultando...' : `Buscar ${selectedOption.label}`}</button></div></form> : <form onSubmit={runBatch} className="query-form"><label>Valores, um por linha</label><textarea className="batch-textarea" value={batchValues} onChange={e => setBatchValues(e.target.value)} placeholder={`${selectedOption.placeholder}\n${selectedOption.placeholder}\n${selectedOption.placeholder}`}/><div className="batch-footer"><span>{batchValues.split(/\r?\n/).filter(Boolean).length} item(ns)</span><button className="primary-button" disabled={status === 'loading'}>{status === 'loading' ? 'Criando lote...' : 'Iniciar lote'}</button></div></form>}{status === 'error' && <div className="login-error">{errorMessage}</div>}</section>}

  {view === 'batch' && <><section className="page-card batch-monitor"><div className="page-card-header"><div><h2>Lotes recentes</h2><p>Acompanhe progresso, falhas e cancelamentos.</p></div><button className="secondary-button" onClick={loadBatches}><RefreshCw size={16}/>Atualizar</button></div>{activeBatch && <div className="active-batch"><div className="batch-summary"><div><strong>{displayCommand(`${activeBatch.commandPrefix} lote`)}</strong><small>{activeBatch.requestedBy} · {new Date(activeBatch.createdAt).toLocaleString('pt-BR')}</small></div><span className={`batch-status ${activeBatch.status.toLowerCase()}`}>{activeBatch.status}</span></div><div className="batch-progress"><span style={{width: `${progress}%`}}/></div><div className="batch-counters"><span>{progress}%</span><span>{activeBatch.completed} concluídas</span><span>{activeBatch.failed} falhas</span><span>{activeBatch.processing} em andamento</span><span>{activeBatch.queued} na fila</span></div><div className="batch-actions">{!['COMPLETED','COMPLETED_WITH_ERRORS'].includes(activeBatch.status) && <button className="danger-button" onClick={() => cancelBatch(activeBatch.id)}><XCircle size={16}/>Cancelar lote</button>}{activeBatch.failed > 0 && ['COMPLETED_WITH_ERRORS','COMPLETED'].includes(activeBatch.status) && <button className="secondary-button" onClick={() => retryBatch(activeBatch.id)}><RefreshCw size={16}/>Repetir falhas</button>}</div><div className="batch-items">{activeBatch.items.map(item => <button key={item.id} onClick={() => { setResult(item); setView('search'); setStatus(item.status === 'FAILED' ? 'error' : 'success'); }}><span>{displayCommand(item.command)}</span><em>{item.status}</em></button>)}</div></div>}<div className="history-list">{batches.map(batch => <article className="history-item" key={batch.id}><button className="history-main" onClick={() => loadBatch(batch.id)}><span><strong>{displayCommand(`${batch.commandPrefix} lote`)}</strong><small>{batch.requestedBy} · {new Date(batch.createdAt).toLocaleString('pt-BR')} · {batch.completed}/{batch.total}</small></span></button><span className={`batch-status ${batch.status.toLowerCase()}`}>{batch.status}</span></article>)}</div></section></>}

  {view === 'search' && <><section className="metrics-grid"><article><span className="metric-icon violet"><Activity size={20}/></span><div><small>Histórico central</small><strong>{history.length}</strong></div><em>Servidor</em></article><article><span className="metric-icon blue"><Clock3 size={20}/></span><div><small>Último tempo</small><strong>{result ? `${(result.elapsedMs/1000).toFixed(1)}s` : '—'}</strong></div><em>API</em></article><article><span className="metric-icon green"><ShieldCheck size={20}/></span><div><small>Usuário</small><strong>{user.name}</strong></div><em>{user.role}</em></article></section><section className="result-card"><div className="result-header"><div><span className={`result-status ${status}`}>{status === 'loading' ? 'PROCESSANDO' : result ? result.status : 'AGUARDANDO'}</span><h2>Resultado da consulta</h2></div>{result && <div className="result-actions"><button className="secondary-button" onClick={() => copyValue('all', result.content)}>{copiedId === 'all' ? <Check size={17}/> : <Copy size={17}/>}Copiar tudo</button><button className="secondary-button" onClick={() => downloadText(result)}><Download size={17}/>Exportar</button></div>}</div>{result ? <div className="result-body">{result.error && <div className="login-error">{result.error}</div>}{parsedFields.length ? <div className="fields-layout">{Object.entries(groupedFields).map(([section, fields]) => <section className="field-section" key={section}><h3>{section}</h3><div className="field-grid">{fields.map(field => <article className="field-card" key={field.id}><div><small>{field.label}</small><strong>{field.value}</strong></div><button onClick={() => copyValue(field.id, field.value)}>{copiedId === field.id ? <Check size={16}/> : <Copy size={16}/>}</button></article>)}</div></section>)}</div> : <pre>{result.content || result.error}</pre>}</div> : <div className="empty-state"><div><Search size={28}/></div><h3>Nenhuma consulta realizada</h3></div>}</section></>}

  {view === 'history' && <section className="page-card"><div className="page-card-header"><div><h2>Consultas anteriores</h2><p>{history.length} resultado(s) salvos no servidor.</p></div><button className="secondary-button" onClick={loadHistory}><RefreshCw size={16}/>Atualizar</button></div>{history.length === 0 ? <div className="empty-state"><h3>Histórico vazio</h3></div> : <div className="history-list">{history.map(item => <article className="history-item" key={item.id}><button className="history-main" onClick={() => { setResult(item); setView('search'); setStatus(item.status === 'FAILED' ? 'error' : 'success'); }}><span><strong>{displayCommand(item.command)}</strong><small>{new Date(item.createdAt).toLocaleString('pt-BR')} · {item.requestedBy} · {item.status}</small></span></button><div className="history-actions"><button onClick={() => copyValue(`h-${item.id}`, item.content)}><Copy size={16}/></button><button onClick={() => downloadText(item)}><Download size={16}/></button></div></article>)}</div>}</section>}
  {view === 'exports' && <section className="page-card"><div className="page-card-header"><div><h2>Arquivos disponíveis</h2><p>Baixe qualquer resultado salvo.</p></div></div><div className="export-grid">{history.filter(item => item.status === 'COMPLETED').map(item => <article className="export-card" key={item.id}><span className="export-icon"><FileText size={22}/></span><div><strong>{displayCommand(item.command)}</strong><small>{new Date(item.createdAt).toLocaleString('pt-BR')} · {item.requestedBy}</small></div><button className="secondary-button" onClick={() => downloadText(item)}><Download size={16}/>Baixar TXT</button></article>)}</div></section>}
  </main></div>;
}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
